### ISSUE TITLE
ouroboros 0.7 not generating borrow_X for tail field with lifetime

### ISSUE THREAD

**Issue by jsgf** [joshua-maros/ouroboros#14]
For example:
```
use ouroboros::self_referencing;

#[self_referencing]
struct Thing {
    head: String,
    #[borrows(head)]
    tail: Wrap<'this>,
}

struct Wrap<'a>(&'a str);

fn main() {
    let t = ThingBuilder {
        head: "hello".to_string(),
        tail_builder: |head| Wrap(head),
    }.build();

    println!("head: {}, tail: {}", t.borrow_head(), t.borrow_tail().0);
}
```
fails with 
```
error[E0599]: no method named `borrow_tail` found for struct `Thing` in the current scope
  --> src/main.rs:18:55
   |
3  | #[self_referencing]
   | ------------------- method `borrow_tail` not found for this
...
18 |     println!("head: {}, tail: {}", t.borrow_head(), t.borrow_tail().0);
   |                                                       ^^^^^^^^^^^ method not found in `Thing`

error: aborting due to previous error
```

If `tail` is just `tail: &'this str` then it works as expected.

**Comment by jsgf** [comment]
It does generate a `with_tail` however.

**Comment by jsgf** [comment]
When I change it to `tail: &'this str`, then it generates wrong documentation for `borrow_tail()`, saying "Provides a **mutable** reference to tail. [...]"

`

**Comment by joshua-maros** [comment]
This behavior is intentional. Internally, creating a `borrow_tail` function in this situation would require converting a `Wrap<'static>` to a `Wrap<'smaller_lifetime>` which will result in a compilation error for contravariant types (i.e., those where instances with a longer-lasting lifetime are more restricted than instances with a shorter-lasting lifetime):
```rust
struct Wrap<'a>(FnOnce(&'a str));

struct Test {
    wrapped: Wrap<'static>
}

impl Test {
    fn borrow_wrapped<'a>(&'a self) -> &'a Wrap<'a> {
        &self.wrapped
    }
}
```
```
error[E0308]: mismatched types
  --> src/main.rs:18:9
   |
18 |         &self.wrapped
   |         ^^^^^^^^^^^^^ lifetime mismatch
   |
   = note: expected reference `&'a Wrap<'a>`
              found reference `&'a Wrap<'static>`
note: the lifetime `'a` as defined on the method body at 17:23...
  --> src/main.rs:17:23
   |
17 |     fn borrow_wrapped<'a>(&'a self) -> &'a Wrap<'a> {
   |                       ^^
   = note: ...does not necessarily outlive the static lifetime
```
Because of this, and because macros cannot determine if a type is co- or contra-variant, I added code to skip generating `borrows_*` for fields that used a lifetime as a template parameter (although it is fine if used as a lifetime on a reference, which is not itself used as a template parameter.) It does, unfortunately, make the API less ergonomic in these cases, but in turn, it prevents compiler errors that would not be fixable by the users of the library.

One way to emulate the functionality of `borrows_*` is like this:
```rust
let tail_ref = t.with_tail(|tail| tail);
```
Unfortunately Rust lacks the notation to encapsulate this bit of code into a function, it only works if you let the compiler figure out the lifetimes on its own.

It looks like the incorrect documentation was a result of how I edited the code to add in the check and skip. I've fixed it and will publish the fix soon.

**Comment by jsgf** [comment]
But the curious thing is that this used to work with version 0.5, which does generate `borrow_tail` in this case.

**Comment by joshua-maros** [comment]
The macro as of version 0.7 is pretty eager to discount a type as not covariant, as there is no way to actually correctly check for it. (Only the compiler knows at a fairly late stage.) I've modified how the logic works so that now in version `0.8.0`, if it cannot determine if a type is covariant, it produces an error asking the programmer to manually add a `#[covariant]` or `#[not_covariant]` annotation. Your original example should now work by adding `#[covariant]` to the definition of `tail:`.
