### ISSUE TITLE
0.13.0 rejects a type parameter which is unused except through its associated type

### ISSUE THREAD

**Issue by kpreid** [joshua-maros/ouroboros#43]
This program compiles with ouroboros 0.12.0, but fails with 0.13.0:

```rust
#[ouroboros::self_referencing]
struct Thing<T: SomeTrait> {
    outer: Vec<<T as SomeTrait>::Assoc>,
    #[borrows(outer)]
    inner2: &'this (),
}

trait SomeTrait {
    type Assoc: 'static;
}
```

```
error[E0284]: type annotations needed
 --> src/foo.rs:1:1
  |
1 | #[ouroboros::self_referencing]
  | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ cannot infer type for type parameter `T` declared on the struct `BorrowedFields`
  |
  = note: cannot satisfy `<_ as foo::SomeTrait>::Assoc == _`
  = note: this error originates in the attribute macro `ouroboros::self_referencing` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This only occurs when `T` itself is not used in the fields, so `T` could be replaced with a parameter taking the associated type directly, instead of going through the trait at all, but perhaps whatever the new restriction is could be fixed, or documented so that users know how to handle it.

**Comment by kpreid** [comment]
I can confirm that the original case from which I reduced the example code now also compiles in ouroboros 0.14.2.
