### PR TITLE
Fix #[derive(Debug,PartialEq,Eq)] no longer working

### LINKED ISSUE #92: derive(Debug) does not compile
Hi,

The following does not compile:
```rust
#[ouroboros::self_referencing]
#[derive(Debug)]
pub struct Struct<'a> {
    bytes: Vec<u8>,
    #[borrows(bytes)]
    slice: &'a [u8],
}
```

```
error: bad syntax
 --> src/lib.rs:4:1
  |
4 | #[derive(Debug)]
  | ^^^^^^^^^^^^^^^^

error: could not compile `ouroboros-private` (lib) due to previous error
```

Neither does this:
```rust
#[derive(Debug)]
#[ouroboros::self_referencing]
pub struct Struct<'a> {
    bytes: Vec<u8>,
    #[borrows(bytes)]
    slice: &'a [u8],
}
```

```
    Checking ouroboros-private v0.1.0 (/home/maxence/bug/ouroboros-private)
error[E0609]: no field `bytes` on type `&Struct<'a>`
 --> src/lib.rs:4:5
  |
4 |     bytes: Vec<u8>,
  |     ^^^^^ unknown field

error[E0609]: no field `slice` on type `&Struct<'a>`
 --> src/lib.rs:6:5
  |
6 |     slice: &'a [u8],
  |     ^^^^^ unknown field

For more information about this error, try `rustc --explain E0609`.
error: could not compile `ouroboros-private` (lib) due to 2 previous errors
```

Im using `rustc 1.72.0-nightly (1c53407e8 2023-05-28)`

### PR DESCRIPTION
**Pull request by jaysonmaw**
Intended to fix #92 

Seems that all the derive's were no longer working 

The bug was introduced in b1cbf32

body previously would resolve to a stream of one ```TokenTree::Group``` with a stream inside but after this change body is a stream of ```TokenTree::Ident``` and ```TokenTree::Punct```

Skipping the "unwrap" of the TokenTree::Group and sending the stream directly to ```parse_derive_token``` fixed the issue.

### CODE REVIEW

**Comment by jaysonmaw** [comment]
I also wonder if it would be a good idea to add a derive attribute onto one of the examples so that it will fail the tests?
(Assuming that's how the CI works, I'm not familiar)

Could also state in the examples or docs that only those 3 derives work, unless I missed it I didn't know until I dug into the code to look for this bug.
