### PR TITLE
fixes #66 -- remove check for target_has_atomic in order to restore MSRV

### LINKED ISSUE #66: 0.15.1 increase MSRV to 1.60
```
     Compiling ouroboros v0.15.1
       Running `rustc --crate-name ouroboros --edition=2018 /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ouroboros-0.15.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -C linker-plugin-lto -C overflow-checks=on -C metadata=991824e5d85b47ec -C extra-filename=-991824e5d85b47ec --out-dir /home/runner/work/cryptography/cryptography/src/rust/target/release/deps -L dependency=/home/runner/work/cryptography/cryptography/src/rust/target/release/deps --extern aliasable=/home/runner/work/cryptography/cryptography/src/rust/target/release/deps/libaliasable-a0690794418a9c48.rmeta --extern ouroboros_macro=/home/runner/work/cryptography/cryptography/src/rust/target/release/deps/libouroboros_macro-bd82fe48d1a0ccd3.so --cap-lints allow`
  error[E0658]: `cfg(target_has_atomic)` is experimental and subject to change
     --> /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/ouroboros-0.15.1/src/lib.rs:368:11
      |
  368 |     #[cfg(target_has_atomic = "ptr")] // alloc::sync is missing if this is false
      |           ^^^^^^^^^^^^^^^^^^^^^^^^^
      |
      = note: see issue #32976 <https://github.com/rust-lang/rust/issues/32976> for more information

```

This feature is not stable until 1.60. Previously ouroboros worked on 1.48 (probably lower as well, but 1.48 is what we test with)

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by alex** [comment]
obviated by other commits to main
